# Checking Metadata and Cleaning False Positives

Once you have your data in R, it is good practice to run data summaries to check for missing tag or receiver deployment metadata and for false positive detections of your tags.  

## Checking for missing metadata

Ensuring your metadata is up to date and accurate means detection data will be be properly linked to your project, and allow other users to benefit fully from the network.

**Missing or incorrect tag metadata** can result in a lack of tag detections in your data. For example, if deployment date is missing or wrong, the tag finder, which processes the data from each receiver in the network, might not look for your tag in the data, or might not look at the appropriate time when the tag is actually active. This will result in missing tags in your detections data.

**Missing or incorrect receiver metadata** can result in a loss of information for both your project and the projects of other Motus users. For example, missing deployment latitude and longitude can result in a loss of information on the location of a receiver. Particularly when the same receiver is moved from one location to another, it is important your metadata reflect this, so that other users can properly analyze their data. Receiving antenna properties

### Tag Metadata

Only tags registered with Motus (<https://motus.org/tag-registration/>) prior to deployment will appear in detection data.  To view a full list of tags registered to your project:

**INSERT CODE**

If previously registered tags are missing from your data, please contact motus@birdscanada.org

Required tag metadata includes deployment start date/time, end date/time if applicable, deployment latitude, deployment longitude, and species.  You can determine which of your tags are missing this metadata as follows:

**INSERT CODE**

Please update missing tag metadata online at <www.motus.org> by logging in to your project and selecting the 'Manage your tags' option.

### Receiver Metadata

To obtain detection data from a receiver, it must be registered online to your project by it's serial number.  Receiver deployments are then required to link the appropriate metadata to each detection.  To determine a list of receivers registered to your project:

***INSERT CODE***

If you are missing any receivers, please register them online through your project management page

Each receiver requires a deployment which includes a deployment name, site, station type, deployment start/end dates/times, latitude, longitude, and antenna properties including port number, antenna type, and bearing. To view a full list of your current deployments:

***INSERT CODE***

To view which current deployments are missing required information:

***INSERT CODE***

Any missing receiver metadata needs to be updated online.

If you have updated any metadata online, you'll need to force an update on the data you have downloaded, it's good practice to check for updates prior to any analysis as other users may have updated metadata associated with your detection files:
```{r tagme5, eval = FALSE}
t <- tagme(projRecv = 123, forceMeta = TRUE)
```


## Searching for false positives

You may need to check it for false positives, particularely at sites with high levels of background noise, below we outline a number of ways to determine if detections are likely false positives.

***NOT DONE***
