<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>R for Motus</title>
  <meta name="description" content="R for Motus">
  <meta name="generator" content="bookdown 0.5 and GitBook 2.6.7">

  <meta property="og:title" content="R for Motus" />
  <meta property="og:type" content="book" />
  
  <meta property="og:image" content="BSC_Motus_Logo.png" />
  
  

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="R for Motus" />
  
  
  <meta name="twitter:image" content="BSC_Motus_Logo.png" />

<meta name="author" content="Tara L. Crewe and Zoe Crysler">


<meta name="date" content="2017-10-18">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="data-checking-metadata.html">
<link rel="next" href="exploring-data-with-the-motus-r-package.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
code > span.kw { color: #007020; font-weight: bold; } /* Keyword */
code > span.dt { color: #902000; } /* DataType */
code > span.dv { color: #40a070; } /* DecVal */
code > span.bn { color: #40a070; } /* BaseN */
code > span.fl { color: #40a070; } /* Float */
code > span.ch { color: #4070a0; } /* Char */
code > span.st { color: #4070a0; } /* String */
code > span.co { color: #60a0b0; font-style: italic; } /* Comment */
code > span.ot { color: #007020; } /* Other */
code > span.al { color: #ff0000; font-weight: bold; } /* Alert */
code > span.fu { color: #06287e; } /* Function */
code > span.er { color: #ff0000; font-weight: bold; } /* Error */
code > span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #880000; } /* Constant */
code > span.sc { color: #4070a0; } /* SpecialChar */
code > span.vs { color: #4070a0; } /* VerbatimString */
code > span.ss { color: #bb6688; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #19177c; } /* Variable */
code > span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code > span.op { color: #666666; } /* Operator */
code > span.bu { } /* BuiltIn */
code > span.ex { } /* Extension */
code > span.pp { color: #bc7a00; } /* Preprocessor */
code > span.at { color: #7d9029; } /* Attribute */
code > span.do { color: #ba2121; font-style: italic; } /* Documentation */
code > span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
</style>

</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><strong><a href="./">R for Motus</a></strong></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>A walk through the use of R for Motus automated radio-telemetry data</a></li>
<li class="chapter" data-level="1" data-path="introduction.html"><a href="introduction.html"><i class="fa fa-check"></i><b>1</b> Introduction</a><ul>
<li class="chapter" data-level="1.1" data-path="introduction.html"><a href="introduction.html#what-this-book-does-not-cover"><i class="fa fa-check"></i><b>1.1</b> What this book does not cover</a></li>
<li class="chapter" data-level="1.2" data-path="introduction.html"><a href="introduction.html#prerequisites"><i class="fa fa-check"></i><b>1.2</b> Prerequisites</a></li>
<li class="chapter" data-level="1.3" data-path="introduction.html"><a href="introduction.html#how-this-book-is-organized"><i class="fa fa-check"></i><b>1.3</b> How this book is organized</a></li>
<li class="chapter" data-level="1.4" data-path="introduction.html"><a href="introduction.html#sample-dataset"><i class="fa fa-check"></i><b>1.4</b> Sample dataset</a></li>
<li class="chapter" data-level="1.5" data-path="introduction.html"><a href="introduction.html#acknowledgements"><i class="fa fa-check"></i><b>1.5</b> Acknowledgements</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="loading-the-motus-r-package.html"><a href="loading-the-motus-r-package.html"><i class="fa fa-check"></i><b>2</b> Loading the Motus R Package</a><ul>
<li class="chapter" data-level="2.1" data-path="loading-the-motus-r-package.html"><a href="loading-the-motus-r-package.html#user-authentication"><i class="fa fa-check"></i><b>2.1</b> User Authentication</a></li>
<li class="chapter" data-level="2.2" data-path="loading-the-motus-r-package.html"><a href="loading-the-motus-r-package.html#internal-data-processing"><i class="fa fa-check"></i><b>2.2</b> Internal data processing</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="accessing-and-understanding-detections-data.html"><a href="accessing-and-understanding-detections-data.html"><i class="fa fa-check"></i><b>3</b> Accessing and understanding detections data</a><ul>
<li class="chapter" data-level="3.1" data-path="accessing-and-understanding-detections-data.html"><a href="accessing-and-understanding-detections-data.html#database-types"><i class="fa fa-check"></i><b>3.1</b> Database types</a></li>
<li class="chapter" data-level="3.2" data-path="accessing-and-understanding-detections-data.html"><a href="accessing-and-understanding-detections-data.html#load-relevant-r-packages"><i class="fa fa-check"></i><b>3.2</b> Load relevant R packages</a></li>
<li class="chapter" data-level="3.3" data-path="accessing-and-understanding-detections-data.html"><a href="accessing-and-understanding-detections-data.html#importing-tag-detections"><i class="fa fa-check"></i><b>3.3</b> Importing tag detections</a></li>
<li class="chapter" data-level="3.4" data-path="accessing-and-understanding-detections-data.html"><a href="accessing-and-understanding-detections-data.html#data-structure"><i class="fa fa-check"></i><b>3.4</b> Data structure</a><ul>
<li class="chapter" data-level="3.4.1" data-path="accessing-and-understanding-detections-data.html"><a href="accessing-and-understanding-detections-data.html#convert-a-virtual-table-to-a-flat-dataframe"><i class="fa fa-check"></i><b>3.4.1</b> Convert a virtual table to a flat dataframe</a></li>
<li class="chapter" data-level="3.4.2" data-path="accessing-and-understanding-detections-data.html"><a href="accessing-and-understanding-detections-data.html#export-your-flat-dataframe-to-a-.csv-file"><i class="fa fa-check"></i><b>3.4.2</b> Export your “flat” dataframe to a .csv file</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="data-checking-metadata.html"><a href="data-checking-metadata.html"><i class="fa fa-check"></i><b>4</b> Data Checking: Metadata</a><ul>
<li class="chapter" data-level="4.1" data-path="data-checking-metadata.html"><a href="data-checking-metadata.html#load-relevant-r-packages-1"><i class="fa fa-check"></i><b>4.1</b> Load relevant R packages</a></li>
<li class="chapter" data-level="4.2" data-path="data-checking-metadata.html"><a href="data-checking-metadata.html#tag-metadata"><i class="fa fa-check"></i><b>4.2</b> Tag Metadata</a><ul>
<li class="chapter" data-level="4.2.1" data-path="data-checking-metadata.html"><a href="data-checking-metadata.html#import-data"><i class="fa fa-check"></i><b>4.2.1</b> Import Data</a></li>
<li class="chapter" data-level="4.2.2" data-path="data-checking-metadata.html"><a href="data-checking-metadata.html#tag-metadata-checks"><i class="fa fa-check"></i><b>4.2.2</b> Tag Metadata Checks</a></li>
<li class="chapter" data-level="4.2.3" data-path="data-checking-metadata.html"><a href="data-checking-metadata.html#receiver-metadata"><i class="fa fa-check"></i><b>4.2.3</b> Receiver Metadata</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="data-checking-metadata.html"><a href="data-checking-metadata.html#searching-for-false-positives"><i class="fa fa-check"></i><b>4.3</b> Searching for false positives</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="cleaning-data-to-remove-false-detections.html"><a href="cleaning-data-to-remove-false-detections.html"><i class="fa fa-check"></i><b>5</b> Cleaning data to remove false detections</a><ul>
<li class="chapter" data-level="5.1" data-path="cleaning-data-to-remove-false-detections.html"><a href="cleaning-data-to-remove-false-detections.html#load-relevant-r-packages-2"><i class="fa fa-check"></i><b>5.1</b> Load relevant R packages</a></li>
<li class="chapter" data-level="5.2" data-path="cleaning-data-to-remove-false-detections.html"><a href="cleaning-data-to-remove-false-detections.html#removing-detections-outside-of-deployment-range"><i class="fa fa-check"></i><b>5.2</b> Removing detections outside of deployment range</a></li>
<li class="chapter" data-level="5.3" data-path="cleaning-data-to-remove-false-detections.html"><a href="cleaning-data-to-remove-false-detections.html#removing-detections-based-on-visual-geographic-positions"><i class="fa fa-check"></i><b>5.3</b> Removing detections based on visual geographic positions</a></li>
<li class="chapter" data-level="5.4" data-path="cleaning-data-to-remove-false-detections.html"><a href="cleaning-data-to-remove-false-detections.html#removing-detections-based-on-estimated-flight-speed"><i class="fa fa-check"></i><b>5.4</b> Removing detections based on estimated flight speed</a></li>
<li class="chapter" data-level="5.5" data-path="cleaning-data-to-remove-false-detections.html"><a href="cleaning-data-to-remove-false-detections.html#removing-false-positives-based-on-hitids"><i class="fa fa-check"></i><b>5.5</b> Removing false positives based on hitID’s</a></li>
<li class="chapter" data-level="5.6" data-path="cleaning-data-to-remove-false-detections.html"><a href="cleaning-data-to-remove-false-detections.html#removing-detections-based-on-automated-filtering"><i class="fa fa-check"></i><b>5.6</b> Removing detections based on automated filtering</a></li>
<li class="chapter" data-level="5.7" data-path="cleaning-data-to-remove-false-detections.html"><a href="cleaning-data-to-remove-false-detections.html#duplicate-tags-and-ambiguous-detections"><i class="fa fa-check"></i><b>5.7</b> Duplicate tags and ambiguous detections</a><ul>
<li class="chapter" data-level="5.7.1" data-path="cleaning-data-to-remove-false-detections.html"><a href="cleaning-data-to-remove-false-detections.html#check-for-ambiguous-tags"><i class="fa fa-check"></i><b>5.7.1</b> Check for ambiguous tags</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="exploring-data-with-the-motus-r-package.html"><a href="exploring-data-with-the-motus-r-package.html"><i class="fa fa-check"></i><b>6</b> Exploring data with the Motus R package</a><ul>
<li class="chapter" data-level="6.1" data-path="exploring-data-with-the-motus-r-package.html"><a href="exploring-data-with-the-motus-r-package.html#summarizing-your-data"><i class="fa fa-check"></i><b>6.1</b> Summarizing your data</a></li>
<li class="chapter" data-level="6.2" data-path="exploring-data-with-the-motus-r-package.html"><a href="exploring-data-with-the-motus-r-package.html#plotting-your-data"><i class="fa fa-check"></i><b>6.2</b> Plotting your data</a></li>
</ul></li>
</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">R for Motus</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="cleaning-data-to-remove-false-detections" class="section level1">
<h1><span class="header-section-number">5</span> Cleaning data to remove false detections</h1>
<p>Background radio noise will sometimes create false positives in your detection data. Some sites will inherently have more background noise than others, and some tag IDs are more prone to false positives than others. Once you download your data, the first step should be cleaning it of false detections. There are a few ways to do this, ultimately it is up to you to determine which detections are true and which should be removed. Below we outline a number of ways to determine if detections are likely false positives.</p>
<div id="load-relevant-r-packages-2" class="section level2">
<h2><span class="header-section-number">5.1</span> Load relevant R packages</h2>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(devtools)
<span class="kw">library</span>(tidyverse)
<span class="kw">library</span>(motus)
<span class="kw">library</span>(lubridate)</code></pre></div>
</div>
<div id="removing-detections-outside-of-deployment-range" class="section level2">
<h2><span class="header-section-number">5.2</span> Removing detections outside of deployment range</h2>
<p>A first step to removing definite false positives, is to remove any detections that fall outside of the tag deployment dates. To do this we will need to import the tagging metadata and merge it with the tag detection files to see tag deployment start/end dates.</p>
<ol style="list-style-type: decimal">
<li><p><strong>Download tag deployment metadata</strong>: from the download page <a href="https://motus.org/data/downloads" class="uri">https://motus.org/data/downloads</a>, select your project from the dropdown menu and click “Tag Deployments” to get a tag-deployments.csv file. Alternatively, you can download the same deployments file from your project tag page.</p></li>
<li><p><strong>Import tag deployment metadata into R</strong></p></li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tagMeta &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;./data/tag-deployments-jb.csv&quot;</span>) ## replace the location with the file path where you saved the .csv file.
## rename columns
tagMeta &lt;-<span class="st"> </span><span class="kw">rename</span>(tagMeta, <span class="dt">motusTagID =</span> tagID, <span class="dt">tagStart =</span> tsStart, <span class="dt">tagEnd =</span> tsEnd)</code></pre></div>
<p>OR (we should probably go this way, and work from the .motus file)</p>
<p>1-2. <strong>Import tag deployment metadata from your .motus file</strong> To import and convert your tag metadata in your .motus file to a flat file (for more information see ‘Accessing Data’ chapter):</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="co">#t &lt;- dplyr::src_sqlite(&quot;./data/project-38.motus&quot;)     # import .motus file from your local directory (change directory to match)</span>
<span class="co">#tagMeta &lt;- tbl(t, &quot;tagDeps&quot;)                          # extract tagDeps table, with tag deployment metadata</span>
<span class="co">#tagMeta &lt;- tagMeta %&gt;% collect %&gt;% as.data.frame      # convert tag metadata to a flat file</span></code></pre></div>
<ol start="3" style="list-style-type: decimal">
<li><strong>Join tag metadata and detection data</strong>: Once you’ve created a flat .csv file of your data (see ‘Accessing Data’ Chapter), you can import using the following statement:</li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">JBraw &lt;-<span class="st"> </span><span class="kw">read.csv</span>(<span class="st">&quot;./data/JB_sample_data_all.csv&quot;</span>)</code></pre></div>
<p>Join the tagMeta database to your detection data, here we only include the start/end date columns from the tagMeta database, however you can choose to keep all columns if necessary.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">JBraw &lt;-<span class="st"> </span>dplyr<span class="op">::</span><span class="kw">left_join</span>(JBraw, <span class="kw">select</span>(tagMeta, tagDeployID, motusTagID, tagStart, tagEnd))</code></pre></div>
<ol start="4" style="list-style-type: decimal">
<li><strong>Remove detections that fall outside tag deployment dates</strong></li>
</ol>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">## first ensure that all times are in POSIXct
JBraw<span class="op">$</span>ts &lt;-<span class="st"> </span><span class="kw">as_datetime</span>(JBraw<span class="op">$</span>ts, <span class="dt">tz =</span> <span class="st">&quot;UTC&quot;</span>)
JBraw<span class="op">$</span>tagStart &lt;-<span class="st"> </span><span class="kw">as_datetime</span>(JBraw<span class="op">$</span>tagStart, <span class="dt">tz =</span> <span class="st">&quot;UTC&quot;</span>)
JBraw<span class="op">$</span>tagEnd &lt;-<span class="st"> </span><span class="kw">as_datetime</span>(JBraw<span class="op">$</span>tagEnd, <span class="dt">tz =</span> <span class="st">&quot;UTC&quot;</span>)
## subset to keep anything within tag deployment range, making sure to account for NAs in end dates
JBraw &lt;-<span class="st"> </span><span class="kw">subset</span>(JBraw, ts <span class="op">&lt;</span><span class="st"> </span>tagEnd <span class="op">|</span><span class="st"> </span><span class="kw">is.na</span>(tagEnd))
JBraw &lt;-<span class="st"> </span><span class="kw">subset</span>(JBraw, ts <span class="op">&gt;</span><span class="st"> </span>tagStart)</code></pre></div>
</div>
<div id="removing-detections-based-on-visual-geographic-positions" class="section level2">
<h2><span class="header-section-number">5.3</span> Removing detections based on visual geographic positions</h2>
<p>A few simple plots of latitude/longitude vs. time can highlight detections that occur in areas outside of the expected geographic range of the species for that date, or flights showing impossible speeds over large distances. First, lets replace any instances with no GPS coordinates with the given locations from receiver deployment metadata:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">## NEED TO ADD SCRIPT
## for now:
JBraw &lt;-<span class="st"> </span><span class="kw">filter</span>(JBraw, lat <span class="op">&gt;</span><span class="st"> </span><span class="dv">0</span>)</code></pre></div>
<p>Now, lets make a simple plot</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">## make lat vs time plots of all tags
## now the data looks better and only tag 16038 looks odd
<span class="kw">ggplot</span>(JBraw, <span class="kw">aes</span>(ts, lat, <span class="dt">group =</span> motusTagID)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_line</span>() <span class="op">+</span><span class="st"> </span><span class="kw">facet_wrap</span>(<span class="op">~</span>motusTagID)</code></pre></div>
<p><img src="MotusRBook_files/figure-html/falseByLat1-1.png" width="672" /> Tag 16038 looks strange, so we can examine that detection period closer, and then remove any hitIDs we disagree with</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">## filter JBraw to only show motusTagID 16038, and only before 2015-10-01
<span class="kw">ggplot</span>(<span class="kw">filter</span>(JBraw, motusTagID <span class="op">==</span><span class="st"> </span><span class="dv">16038</span> <span class="op">&amp;</span><span class="st"> </span>ts <span class="op">&lt;</span><span class="st"> </span><span class="kw">as.POSIXct</span>(<span class="st">&quot;2015-10-01&quot;</span>)), <span class="kw">aes</span>(ts, lat, <span class="dt">group =</span> motusTagID)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_line</span>() <span class="op">+</span><span class="st"> </span><span class="kw">facet_wrap</span>(<span class="op">~</span>motusTagID)</code></pre></div>
<p><img src="MotusRBook_files/figure-html/falseByLat2-1.png" width="672" /> It is highly unlikely/implausible that this bird travelled such a distance in one day, especially returning to the same receiver, but to confirm we can examine the signal strength of the potentially false detections.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">## this time filter by motusTagID and by latitude so we only see the strange detections
<span class="kw">ggplot</span>(<span class="kw">filter</span>(JBraw, motusTagID <span class="op">==</span><span class="st"> </span><span class="dv">16038</span> <span class="op">&amp;</span><span class="st"> </span>lat <span class="op">&lt;</span><span class="st"> </span><span class="dv">42</span>), <span class="kw">aes</span>(ts, sig, <span class="dt">colour =</span> <span class="kw">as.factor</span>(ant))) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">facet_wrap</span>(<span class="op">~</span>motusTagID)</code></pre></div>
<p><img src="MotusRBook_files/figure-html/falseByLat3-1.png" width="672" /> It appears that there were only two detections at this receiver, both detections were captured by all 3 antennas, and they were over a minute apart. Since the burst rate of this tag is 6.09 seconds, we know that these are not consecutive detections. These detections are false positives. So lets identify the hitIDs so we can remove them later.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">## using a filter that will provide us with only the spurious detections:
<span class="kw">filter</span>(JBraw, motusTagID <span class="op">==</span><span class="st"> </span><span class="dv">16038</span> <span class="op">&amp;</span><span class="st"> </span>lat <span class="op">&lt;</span><span class="st"> </span><span class="dv">42</span>)</code></pre></div>
<pre><code>##      X     hitID    runID batchID                  ts      sig freqsd
## 1 3128 239875440 18377606   83952 2015-08-21 02:13:54 -64.8776 0.0183
## 2 3129 239875441 18377606   83952 2015-08-21 02:15:13 -65.1202 0.0188
## 3 3130 239875442 18377607   83952 2015-08-21 02:13:54 -55.2240 0.0240
## 4 3131 239875443 18377607   83952 2015-08-21 02:15:13 -55.2760 0.0121
## 5 3132 239875444 18377608   83952 2015-08-21 02:13:54 -52.0967 0.0470
## 6 3133 239875445 18377608   83952 2015-08-21 02:15:13 -51.6143 0.0127
##   motusTagID ant runLen tagProjID  id tagDeployID  depLat depLon
## 1      16038   1      2        38 180        1826 51.4839 -80.45
## 2      16038   1      2        38 180        1826 51.4839 -80.45
## 3      16038   2      2        38 180        1826 51.4839 -80.45
## 4      16038   2      2        38 180        1826 51.4839 -80.45
## 5      16038   3      2        38 180        1826 51.4839 -80.45
## 6      16038   3      2        38 180        1826 51.4839 -80.45
##   recvDeployID            recv               site projID antType
## 1         2566 SG-1215BBBK1163 Illini State Park      80  yagi-5
## 2         2566 SG-1215BBBK1163 Illini State Park      80  yagi-5
## 3         2566 SG-1215BBBK1163 Illini State Park      80  yagi-5
## 4         2566 SG-1215BBBK1163 Illini State Park      80  yagi-5
## 5         2566 SG-1215BBBK1163 Illini State Park      80  yagi-5
## 6         2566 SG-1215BBBK1163 Illini State Park      80  yagi-5
##   antBearing                   spEN  tagProj    proj     lat    lon   alt
## 1        110 Semipalmated Sandpiper JamesBay Shoener 41.3272 -88.74 156.8
## 2        110 Semipalmated Sandpiper JamesBay Shoener 41.3272 -88.74 156.8
## 3         85 Semipalmated Sandpiper JamesBay Shoener 41.3272 -88.74 156.8
## 4         85 Semipalmated Sandpiper JamesBay Shoener 41.3272 -88.74 156.8
## 5        230 Semipalmated Sandpiper JamesBay Shoener 41.3272 -88.74 156.8
## 6        230 Semipalmated Sandpiper JamesBay Shoener 41.3272 -88.74 156.8
##              tagStart tagEnd
## 1 2015-08-17 10:30:00   &lt;NA&gt;
## 2 2015-08-17 10:30:00   &lt;NA&gt;
## 3 2015-08-17 10:30:00   &lt;NA&gt;
## 4 2015-08-17 10:30:00   &lt;NA&gt;
## 5 2015-08-17 10:30:00   &lt;NA&gt;
## 6 2015-08-17 10:30:00   &lt;NA&gt;</code></pre>
<p>We can see that the hitIDs we want to remove are 239875440 - 239875445. For now we will keep them in the data to continue looking for false positives. We will remove all of them together at the end of this chapter.</p>
</div>
<div id="removing-detections-based-on-estimated-flight-speed" class="section level2">
<h2><span class="header-section-number">5.4</span> Removing detections based on estimated flight speed</h2>
<p>By looking at the rate of movement between sites with consicutive detections, we can quickly view flights that are not physically possible. Further examination of these detections will be required to determine which detections are true and which are false. Rate of movement between sites can be determined using the siteTrans function in the motus R package. For instructions on installing the package, see chapter “Loading Packages”.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">JBtrans &lt;-<span class="st"> </span><span class="kw">siteTrans</span>(JBraw) ## create new data.base consisting of transitions between consecutive sites for each tag
<span class="kw">head</span>(JBtrans)</code></pre></div>
<pre><code>## # A tibble: 6 x 15
## # Groups:   motusTagID, tagDeployID [1]
##   motusTagID tagDeployID                ts.x   lat.x    lon.x
##        &lt;int&gt;       &lt;int&gt;              &lt;dttm&gt;   &lt;dbl&gt;    &lt;dbl&gt;
## 1      16037        1825 2015-08-17 17:02:39 51.4793 -80.4337
## 2      16037        1825 2015-08-28 16:40:18 51.4839 -80.4501
## 3      16037        1825 2015-09-08 01:10:13 51.2913 -80.1168
## 4      16037        1825 2015-09-08 18:37:16 44.5809 -65.7928
## 5      16037        1825 2015-09-13 19:46:27 39.0283 -74.8100
## 6      16037        1825 2015-09-14 15:56:49 37.1499 -75.9572
## # ... with 10 more variables: site.x &lt;fctr&gt;, ts.y &lt;dttm&gt;, lat.y &lt;dbl&gt;,
## #   lon.y &lt;dbl&gt;, site.y &lt;fctr&gt;, tot_ts &lt;time&gt;, dist &lt;dbl&gt;, rate &lt;dbl&gt;,
## #   bearing &lt;dbl&gt;, rhumbline_bearing &lt;dbl&gt;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">## so we see that tag 16047 has lots of high speeds due to close towers - 16038 has high speeds due to false detections
## same as what we saw with the plots, so lets remove those hitIDs
tmp &lt;-<span class="st"> </span><span class="kw">filter</span>(JBraw, <span class="op">!</span>(hitID <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="dv">239875440</span>, <span class="dv">239875441</span>, <span class="dv">239875442</span>, <span class="dv">239875443</span>, <span class="dv">239875444</span>, <span class="dv">239875445</span>)))</code></pre></div>
<p>The resulting database JBtrans shows information on the last detection at site x, and the first detection at site y. So in the above table, we can see the total time, distance, rate of movement, bearing, and rhumbline_bearing of potential flights between sites. Rate of movement is presented as m/s. Because rate of movement is based on receiver location at the time of last and first detection at two sites, it is only an estimation and sites closer together will have less accurate results. For example, lets look at row 58 from JBtrans:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">JBtrans[<span class="dv">58</span>,]</code></pre></div>
<pre><code>## # A tibble: 1 x 15
## # Groups:   motusTagID, tagDeployID [1]
##   motusTagID tagDeployID                ts.x  lat.x    lon.x    site.x
##        &lt;int&gt;       &lt;int&gt;              &lt;dttm&gt;  &lt;dbl&gt;    &lt;dbl&gt;    &lt;fctr&gt;
## 1      16047        1839 2015-10-26 11:27:54 42.488 -72.5376 MountToby
## # ... with 9 more variables: ts.y &lt;dttm&gt;, lat.y &lt;dbl&gt;, lon.y &lt;dbl&gt;,
## #   site.y &lt;fctr&gt;, tot_ts &lt;time&gt;, dist &lt;dbl&gt;, rate &lt;dbl&gt;, bearing &lt;dbl&gt;,
## #   rhumbline_bearing &lt;dbl&gt;</code></pre>
<p>It would appear that the bird is travelling at a rage of 2203.543 m/s (7,932 km/hr)! Based on rate alone you may think this is due to false detections, however the two sites are only 22km apart, and the time between detections was only 10 seconds. This high estimated rate of movement is likely due to the tag being detected at the edge of the detection range of both receivers; remember we do not know how far the tag is from the receiver location at time of detection. It’s therefore important to take all information into consideration when looking at high rates of movement. Let’s look at all cases of high rates of movements, we can be conservative and only look at rates &gt; 50 m/s</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">filter</span>(JBtrans, rate <span class="op">&gt;</span><span class="st"> </span><span class="dv">50</span>)</code></pre></div>
<pre><code>## # A tibble: 23 x 15
## # Groups:   motusTagID, tagDeployID [2]
##    motusTagID tagDeployID                ts.x   lat.x    lon.x
##         &lt;int&gt;       &lt;int&gt;              &lt;dttm&gt;   &lt;dbl&gt;    &lt;dbl&gt;
##  1      16038        1826 2015-08-20 22:51:11 51.4839 -80.4501
##  2      16047        1839 2015-10-26 11:19:40 42.6807 -72.4739
##  3      16047        1839 2015-10-26 11:19:49 42.6070 -72.7166
##  4      16047        1839 2015-10-26 11:19:59 42.6807 -72.4739
##  5      16047        1839 2015-10-26 11:20:28 42.6070 -72.7166
##  6      16047        1839 2015-10-26 11:20:48 42.6807 -72.4739
##  7      16047        1839 2015-10-26 11:21:17 42.6070 -72.7166
##  8      16047        1839 2015-10-26 11:21:46 42.6807 -72.4739
##  9      16047        1839 2015-10-26 11:21:55 42.6070 -72.7166
## 10      16047        1839 2015-10-26 11:22:34 42.6807 -72.4739
## # ... with 13 more rows, and 10 more variables: site.x &lt;fctr&gt;,
## #   ts.y &lt;dttm&gt;, lat.y &lt;dbl&gt;, lon.y &lt;dbl&gt;, site.y &lt;fctr&gt;, tot_ts &lt;time&gt;,
## #   dist &lt;dbl&gt;, rate &lt;dbl&gt;, bearing &lt;dbl&gt;, rhumbline_bearing &lt;dbl&gt;</code></pre>
<p>Almost all of these flights are between stations that are &lt; 30 km apart so high rates of movement are not surprising. Only one flight had an impossible rate of movement with stations far apart:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">filter</span>(JBtrans, rate <span class="op">&gt;</span><span class="st"> </span><span class="dv">50</span> <span class="op">&amp;</span><span class="st"> </span>dist <span class="op">&gt;</span><span class="st"> </span><span class="dv">40000</span>)</code></pre></div>
<pre><code>## # A tibble: 1 x 15
## # Groups:   motusTagID, tagDeployID [1]
##   motusTagID tagDeployID                ts.x   lat.x    lon.x      site.x
##        &lt;int&gt;       &lt;int&gt;              &lt;dttm&gt;   &lt;dbl&gt;    &lt;dbl&gt;      &lt;fctr&gt;
## 1      16038        1826 2015-08-20 22:51:11 51.4839 -80.4501 North Bluff
## # ... with 9 more variables: ts.y &lt;dttm&gt;, lat.y &lt;dbl&gt;, lon.y &lt;dbl&gt;,
## #   site.y &lt;fctr&gt;, tot_ts &lt;time&gt;, dist &lt;dbl&gt;, rate &lt;dbl&gt;, bearing &lt;dbl&gt;,
## #   rhumbline_bearing &lt;dbl&gt;</code></pre>
<p>Not surprisingly, this is the same tag we identified as having false positives when examining latitudinal plots above. We can confirm the hitID’s by making the same plots as above, or similar ones identifying site name:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">ggplot</span>(<span class="kw">filter</span>(JBraw, motusTagID <span class="op">==</span><span class="st"> </span><span class="dv">16038</span>), <span class="kw">aes</span>(ts, lat, <span class="dt">col =</span> <span class="kw">as.factor</span>(site))) <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>()</code></pre></div>
<p><img src="MotusRBook_files/figure-html/falseBySpeed5-1.png" width="672" /> We can see that the detections at Illini State Park are the spurious detections, so to determine their hitIDs we can filter by site:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">filter</span>(JBraw, motusTagID <span class="op">==</span><span class="st"> </span><span class="dv">16038</span> <span class="op">&amp;</span><span class="st"> </span>site <span class="op">==</span><span class="st"> &quot;Illini State Park &quot;</span>)</code></pre></div>
<pre><code>##      X     hitID    runID batchID                  ts      sig freqsd
## 1 3128 239875440 18377606   83952 2015-08-21 02:13:54 -64.8776 0.0183
## 2 3129 239875441 18377606   83952 2015-08-21 02:15:13 -65.1202 0.0188
## 3 3130 239875442 18377607   83952 2015-08-21 02:13:54 -55.2240 0.0240
## 4 3131 239875443 18377607   83952 2015-08-21 02:15:13 -55.2760 0.0121
## 5 3132 239875444 18377608   83952 2015-08-21 02:13:54 -52.0967 0.0470
## 6 3133 239875445 18377608   83952 2015-08-21 02:15:13 -51.6143 0.0127
##   motusTagID ant runLen tagProjID  id tagDeployID  depLat depLon
## 1      16038   1      2        38 180        1826 51.4839 -80.45
## 2      16038   1      2        38 180        1826 51.4839 -80.45
## 3      16038   2      2        38 180        1826 51.4839 -80.45
## 4      16038   2      2        38 180        1826 51.4839 -80.45
## 5      16038   3      2        38 180        1826 51.4839 -80.45
## 6      16038   3      2        38 180        1826 51.4839 -80.45
##   recvDeployID            recv               site projID antType
## 1         2566 SG-1215BBBK1163 Illini State Park      80  yagi-5
## 2         2566 SG-1215BBBK1163 Illini State Park      80  yagi-5
## 3         2566 SG-1215BBBK1163 Illini State Park      80  yagi-5
## 4         2566 SG-1215BBBK1163 Illini State Park      80  yagi-5
## 5         2566 SG-1215BBBK1163 Illini State Park      80  yagi-5
## 6         2566 SG-1215BBBK1163 Illini State Park      80  yagi-5
##   antBearing                   spEN  tagProj    proj     lat    lon   alt
## 1        110 Semipalmated Sandpiper JamesBay Shoener 41.3272 -88.74 156.8
## 2        110 Semipalmated Sandpiper JamesBay Shoener 41.3272 -88.74 156.8
## 3         85 Semipalmated Sandpiper JamesBay Shoener 41.3272 -88.74 156.8
## 4         85 Semipalmated Sandpiper JamesBay Shoener 41.3272 -88.74 156.8
## 5        230 Semipalmated Sandpiper JamesBay Shoener 41.3272 -88.74 156.8
## 6        230 Semipalmated Sandpiper JamesBay Shoener 41.3272 -88.74 156.8
##              tagStart tagEnd
## 1 2015-08-17 10:30:00   &lt;NA&gt;
## 2 2015-08-17 10:30:00   &lt;NA&gt;
## 3 2015-08-17 10:30:00   &lt;NA&gt;
## 4 2015-08-17 10:30:00   &lt;NA&gt;
## 5 2015-08-17 10:30:00   &lt;NA&gt;
## 6 2015-08-17 10:30:00   &lt;NA&gt;</code></pre>
<p>Once again we determine that we should remove hitID’s 239875440 - 239875445.</p>
</div>
<div id="removing-false-positives-based-on-hitids" class="section level2">
<h2><span class="header-section-number">5.5</span> Removing false positives based on hitID’s</h2>
<p>Now that we have a list of hitID’s that we have determined to be false positives, we can easily remove them from our database</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">JBfiltered &lt;-<span class="st"> </span><span class="kw">filter</span>(JBraw, <span class="op">!</span>(hitID <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="dv">239875440</span>, <span class="dv">239875441</span>, <span class="dv">239875442</span>, <span class="dv">239875443</span>, <span class="dv">239875444</span>, <span class="dv">239875445</span>)))</code></pre></div>
</div>
<div id="removing-detections-based-on-automated-filtering" class="section level2">
<h2><span class="header-section-number">5.6</span> Removing detections based on automated filtering</h2>
<p>You can also remove spurious detections through some simple automated filters if you do not wish to examine each tag individually. But note that by applying a general filter to all your detections, you risk removing true detections as well. Detections can be filtered by freqsd or by runLen.<br />
<strong>freqsd</strong> refers to the standard deviation of frequency offset among pulses in a burst, in kHz. Values larger than 0.1 kHz suggest a bogus detection, however this is for detections on SensorGnomes only.<br />
<strong>runLen</strong> is the number of tag bursts in the current run, a run is defined as a group of consecutive detections of a tag detected on a receiver. If you decide to run these filters on your data, it is recommended that you identify the detections you would be removing and examine them to ensure you aren’t removing an unwanted amount of true detections.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">## first convert freqsd to NA for all Lotek receivers
JBraw<span class="op">$</span>freqsd &lt;-<span class="st"> </span><span class="kw">ifelse</span>(<span class="kw">grepl</span>(<span class="st">&quot;Lotek&quot;</span>, JBraw<span class="op">$</span>recv), <span class="st">&quot;NA&quot;</span>,JBraw<span class="op">$</span>freqsd)
## identify which detections would be removed by creating a new column &quot;filter&quot;
JBraw<span class="op">$</span>filter &lt;-<span class="st"> &quot;KEEP&quot;</span>
JBraw<span class="op">$</span>filter[JBraw<span class="op">$</span>runLen <span class="op">&lt;=</span><span class="st"> </span><span class="dv">2</span> <span class="op">&amp;</span><span class="st"> </span>JBraw<span class="op">$</span>freqsd <span class="op">&gt;=</span><span class="st"> </span><span class="fl">0.1</span>] &lt;-<span class="st"> &quot;FILTER&quot;</span></code></pre></div>
<p>Based on these filters, we can summarize how many detections would be removed based on tag, site, or receiver type:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">## potential detections to filter by site
<span class="kw">table</span>(JBraw<span class="op">$</span>filter, JBraw<span class="op">$</span>site)</code></pre></div>
<pre><code>##         
##          Assateague State Park BennettMeadow BISE Blandford Bombay Hook
##   FILTER                     0             0    4         0           0
##   KEEP                       6            27   40         2         121
##         
##          Brier2 BULL Comeau (Marshalltown) D&#39;Estimauville FINWR
##   FILTER      0    0                     0              1     0
##   KEEP       41   69                     6             73   148
##         
##          Flamborough_Quarry FortRiver GWASS Hillman_Marsh Hogback
##   FILTER                  4         0     0             2      18
##   KEEP                    0         0     5             0      41
##         
##          Illini State Park  Kamouraska Koffler Longridge LOOKSPT Machias
##   FILTER                  0          0       1         0       0       0
##   KEEP                    6          0       1       158     110       0
##         
##          Mount Thom MountToby Netitishi North Bluff NP mobile  NWW Old Cut
##   FILTER          0         2         0           3         0    4      12
##   KEEP            0         6      2145         681        32    0       6
##         
##          Piskwamish Port Maitland Prime Hook Ruby&#39;s Sable West Light 2
##   FILTER          0             0          0      0                 28
##   KEEP          224            42         82      0                 25
##         
##          SBWL1 Shelburne Southwest Head St Denis Sur Mer Swallowtail TRUS
##   FILTER    10         0              0                0           1    4
##   KEEP       4         5             65                0          25    8</code></pre>
<p>Sable West Light 2, and Hogback seem to have relatively higher numbers of spurious detections, note that it didn’t filter out the false positives at Illini State Park</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">## potential detections to filter by motusTagID
<span class="kw">table</span>(JBraw<span class="op">$</span>filter, JBraw<span class="op">$</span>motusTagID)</code></pre></div>
<pre><code>##         
##          16035 16036 16037 16038 16039 16044 16047 16048
##   FILTER     0     0    10    40    10     2    31     1
##   KEEP     456   118  1342   122  1116   303   760    97</code></pre>
<p>motusTagID 16038 seems to have a higher number of spurious detections</p>
<p>From here it is a judgement call whether to filter based on freqsd or runLen, and how strict to make the filters. You may wish to apply them only to certain sites or certain tag IDs. There is a balance between removing all questionable detections along with some true detections, vs keeping all detections and potentially having some false positives. To filter based on the above criteria:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">JBraw &lt;-<span class="st"> </span><span class="kw">filter</span>(JBraw, filter <span class="op">==</span><span class="st"> &quot;KEEP&quot;</span>)</code></pre></div>
<p>Ultimately, how strictly you filter your detection data is up to each individual, but it is well worth your time to work through some or all of these methods to be confident in the accuracy of your detection data.</p>

</div>
<div id="duplicate-tags-and-ambiguous-detections" class="section level2">
<h2><span class="header-section-number">5.7</span> Duplicate tags and ambiguous detections</h2>
<p>Duplicate tags occur when there are two or more tags with the same Lotek ID code, burst interval, and nominal transmit frequency (i.e., tags are indistinguishable).</p>
<p>The tag finder program only looks for tags in the raw detetions data during their active lifetimes. Tag lifetimes are estimated based on tag metadata, including deployment date, tag model (battery size), and burst interval. If duplicate tags do not overlap in their active lifetimes, there is no ambiguity in terms of which project and tag the detections belongs to, and each detection is assigned unambiguously to the correct project and tag. This is by far the most common situation for duplicate tags in the Motus system.</p>
<p>In the rare situation when duplicate tags are deployed with overlapping lifetimes, this can result in ambiguous tag detections, where more than one tag (up to 6) could be the source of those detections. In your detections data, these ambiguous detections are identified by a unique negative value in the ‘motusTagID’.</p>
<div id="check-for-ambiguous-tags" class="section level3">
<h3><span class="header-section-number">5.7.1</span> Check for ambiguous tags</h3>
<p>First, make a list of motusTagIDs in your detections data. If your motusTagIDs are all &gt; 0, then you don’t have ambiguous detections in your data.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">select</span>(df.flat, motusTagID) <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">distinct</span>() <span class="op">%&gt;%</span><span class="st"> </span><span class="kw">arrange</span>(motusTagID)</code></pre></div>
<pre><code>##    motusTagID
## 1       10465
## 2       10466
## 3       10467
## 4       10468
## 5       10469
## 6       10470
## 7       10471
## 8       10472
## 9       10473
## 10      10474
## 11      10475
## 12      10476
## 13      10477
## 14      10478
## 15      10479
## 16      10480
## 17      10481
## 18      10482
## 19      10483
## 20      10485
## 21      10486
## 22      10487
## 23      10488
## 24      10489
## 25      10490
## 26      10491
## 27      10492
## 28      10493
## 29      10494
## 30      10495
## 31      10496
## 32      10498
## 33      10499
## 34      10500
## 35      10501
## 36      10502
## 37      10503
## 38      10504
## 39      10506
## 40      17367
## 41      17368
## 42      17369
## 43      17370
## 44      17371
## 45      17372
## 46      17373
## 47      17374
## 48      17375
## 49      17376
## 50      17378
## 51      17380
## 52      17381
## 53      17382
## 54      17383
## 55      17384
## 56      17386
## 57      17387
## 58      17389
## 59      17390
## 60      17391
## 61      17392
## 62      17394
## 63      17395
## 64      17396
## 65      17398
## 66      17399</code></pre>
<p>In this case, there are several ambiguities in the data.</p>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="data-checking-metadata.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="exploring-data-with-the-motus-r-package.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"google": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"download": ["MotusRBook.pdf"],
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(script.src))
      script.src  = script.src.replace(/^https?:/, '');
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
